"""
Core module exports for Anki Discord Toolkit.
"""

from .config import ConfigManager, config
from .constants import (
    ADDON_AUTHOR,
    ADDON_NAME,
    ADDON_PACKAGE,
    ADDON_SHORT_NAME,
    ADDON_VERSION,
    COLOR_ACCENT_PRIMARY,
    COLOR_BORDER,
    COLOR_ERROR,
    COLOR_PURE_BLACK,
    COLOR_SUCCESS,
    COLOR_SURFACE_DARK,
    COLOR_SURFACE_SECONDARY,
    COLOR_SURFACE_TERTIARY,
    COLOR_TEXT_PRIMARY,
    COLOR_TEXT_SECONDARY,
    COLOR_WARNING,
    DEFAULT_CONFIG_FILENAME,
    DISCORD_COMMAND_DECKS,
    DISCORD_COMMAND_HELP,
    DISCORD_COMMAND_PING,
    DISCORD_COMMAND_PREFIX,
    DISCORD_COMMAND_STATUS,
    FIELD_BACK,
    FIELD_CLOZE,
    FIELD_DECK,
    FIELD_EXTRA,
    FIELD_FRONT,
    FIELD_NOTE_TYPE,
    FIELD_TAGS,
    FIELD_TEMPLATE,
    FIELD_TYPE,
    LOG_FILENAME,
    MAIN_MENU_TITLE,
    SUPPORTED_TEMPLATES,
    TOOLS_MENU_ENTRY,
)
from .event_bus import EventBus, event_bus
from .exceptions import (
    AnkiAdapterError,
    ConfigurationError,
    DiscordToolkitError,
    DuplicateCardError,
    ParserError,
    RateLimitExceededError,
    RoutingError,
    SecurityError,
    SyncQueueError,
    ThemeEngineError,
    ValidationError,
)
from .logger import ToolkitLogger, logger

__all__ = [
    "config",
    "ConfigManager",
    "logger",
    "ToolkitLogger",
    "event_bus",
    "EventBus",
    "DiscordToolkitError",
    "ConfigurationError",
    "ParserError",
    "ValidationError",
    "SecurityError",
    "RateLimitExceededError",
    "RoutingError",
    "AnkiAdapterError",
    "DuplicateCardError",
    "SyncQueueError",
    "ThemeEngineError",
    "ADDON_NAME",
    "ADDON_SHORT_NAME",
    "ADDON_PACKAGE",
    "ADDON_VERSION",
    "ADDON_AUTHOR",
]
